---
title: "Saturated"
author: "Alex Wood"
date: "May 7, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#loadings
```{r}
library(tidyverse)
library(ggplot2)
```


#read it in

```{r}
#bring it in
realSat <- read_csv(here::here("realSat.csv"))

realSat
#make into data frame
saturation=realSat
#make into data frame
saturation=as.data.frame(saturation)


#save one for later with all variables
satSave=saturation

```

#whittle it down!
```{r}
#remove characters
saturation=saturation[,-1]
saturation=saturation[,-1]
saturation=saturation[,-1]
saturation

satMatrix=matrix(as.numeric(unlist(saturation)), nrow=nrow(saturation))
#no nas
satMatrix[!rowSums(!is.finite(satMatrix)),]
satMatrix[!is.finite(satMatrix)] <- 0
```
#PCA
```{r}
#scale it
x1=scale(satMatrix, center=TRUE, scale=TRUE)
#make sure there are no nas
x1[!rowSums(!is.finite(x1)),]
x1[!is.finite(x1)] <- 0



#linear algebra to calculate your covariance matrix

#covariance matrix
coSat=(t(x1)%*%x1/(nrow(x1)-1))
head(coSat)

#correlation is standard covariance!
head(cor(satMatrix))


#find a matrix ("P") (our EOFs) that we can multiply by our original matrix to turn it into orthogonal indices (our PCs).

#use svd() on covariance matrix.
out2=svd(coSat)

#look at names
names(out2)

#look at diagnol
save4l8er2=diag(out2$d)

#look at sum of saved for later...should be PCA
sum(save4l8er2)
print(save4l8er2)
#11

#project data onto new axes
PCs2=(x1%*%out2$v)
#11 of them
dim(PCs2)
cov(PCs2)


#total covariance
sum(out2$d)
#11 because it is normalized

#how much of each dataset variability is represented by each PC
fracVariance2=out2$d/sum(out2$d)
fracVariance2
dim(fracVariance2)


# [1] 4.187441e-01 3.461850e-01 1.719439e-01 2.835371e-02 1.937701e-02 8.877331e-03 5.966391e-03
#  [8] 4.780208e-04 6.950682e-05 4.192625e-06 8.821132e-07

#save for later one
sum(save4l8er2)
#28
out2$d/sum(out2$d)

```
```{r}
#make x the same as pcas...there is 50 of them!
x2=c(1:11)


ggplot()+geom_point(aes(x=x2, y=fracVariance2))+ggtitle("Fraction of Variance in Each PCA")+xlab("PCA")+ylab("Percent Variance")

```
#the good stuff..do the PCA plotting work
```{r}
#look at it
head(gcData)


#data frame with the original data, and PCs...combine "saturation" names with PCS
df2 = cbind(as.data.frame(PCs2),saturation[1:nrow(x1),]) 


#remove na from satSave
satSave=satSave[-51,]
#merge them with formation name

#check size
dim(df2)
dim(satSave)
#cut a row off
df2=df2[-51,]
df2=df2[-51,]

#now bind
df2=cbind(df2, satSave$Formation)

#renamed unit
colnames(df2)[colnames(df2)=="satSave$Formation"] <- "Unit"

#as a data.frame, it converts them to v1, v2 and v3, etc.. 
#and eigenvectors (out2$v) with names from the saturation columns
df3 = cbind(as.data.frame(out2$v),names(saturation))
dim(df3)

#rename as saturation
colnames(df3)[colnames(df3)=="names(saturation)"] <- "names"

#get bottom NA out
df2
df3


#and make an awesome plot, we're going to compare PC1 and PC2

ggplot(df2, aes(x = V1, y= V2))+geom_point(aes(colour=Unit),size=6)+
  #first just plotting points and colouring them by the cut
  
  geom_hline(yintercept=0)+geom_vline(xintercept=0)+
  
  #then we'll plot some 0 lines for our reference
  coord_fixed(xlim=c(-4,4),ylim=c(-4,4))+
  
  #and set the scale
  geom_segment(data=df3,aes(x=0,y=0,xend = V1*arrowScale, yend = V2*arrowScale))+
  
  #Now we'll add lines that correspond to our eigen vectors
  geom_text(data=df3,aes(x = V1*arrowScale, y = V2*arrowScale,label=names))
  #and label those lines

saturationPC=ggplot(df2, aes(x = V1, y= V2))+geom_point(aes(colour=Unit),size=6)+
  #first just plotting points and colouring them by the cut
  
  geom_hline(yintercept=0)+geom_vline(xintercept=0)+
  
  #then we'll plot some 0 lines for our reference
  coord_fixed(xlim=c(-4,4),ylim=c(-4,4))+
  
  #and set the scale
  geom_segment(data=df3,aes(x=0,y=0,xend = V1*arrowScale, yend = V2*arrowScale))+
  
  #Now we'll add lines that correspond to our eigen vectors
  geom_text(data=df3,aes(x = V1*arrowScale, y = V2*arrowScale,label=names))
  #and label those lines


ggsave("saturation index.jpg", width = 15, height = 15, units = "in")

```
#now PCA with month
```{r}
#look at it
satSave=satSave[-7,]
satSave

#data frame with the original data, and PCs...combine "saturation" names with PCS
df2 = cbind(as.data.frame(PCs2),saturation[1:nrow(x1),]) 


#remove na from satSave
satSave=satSave[-51,]
#merge them with formation name

#check size
dim(df2)
dim(satSave)
#cut a row off
df2=df2[-51,]
df2=df2[-51,]
df2=df2[-50,]
#now bind
df2=cbind(df2, satSave$Season)

#renamed unit
colnames(df2)[colnames(df2)=="satSave$Season"] <- "Month"

#as a data.frame, it converts them to v1, v2 and v3, etc.. 
#and eigenvectors (out2$v) with names from the saturation columns
df3 = cbind(as.data.frame(out2$v),names(saturation))
dim(df3)

#rename as saturation
colnames(df3)[colnames(df3)=="names(saturation)"] <- "names"

#get bottom NA out
df2
df3


#and make an awesome plot, we're going to compare PC1 and PC2

ggplot(df2, aes(x = V1, y= V2))+geom_point(aes(colour=Month),size=6)+
  #first just plotting points and colouring them by the cut
  
  geom_hline(yintercept=0)+geom_vline(xintercept=0)+
  
  #then we'll plot some 0 lines for our reference
  coord_fixed(xlim=c(-4,4),ylim=c(-4,4))+
  
  #and set the scale
  geom_segment(data=df3,aes(x=0,y=0,xend = V1*arrowScale, yend = V2*arrowScale))+
  
  #Now we'll add lines that correspond to our eigen vectors
  geom_text(data=df3,aes(x = V1*arrowScale, y = V2*arrowScale,label=names))
  #and label those lines


ggsave("monthly saturation.jpg", width = 15, height = 15, units = "in")

```
#now PCA with springs
```{r}
#look at it
satSave=satSave[-7,]
satSave

#data frame with the original data, and PCs...combine "saturation" names with PCS
df2 = cbind(as.data.frame(PCs2),saturation[1:nrow(x1),]) 


#remove na from satSave
satSave=satSave[-51,]
#merge them with formation name

#check size
dim(df2)
dim(satSave)
#cut a row off
df2=df2[-51,]
df2=df2[-51,]
df2=df2[-50,]
#now bind
df2=cbind(df2, satSave$Spring)

#renamed unit
colnames(df2)[colnames(df2)=="satSave$Spring"] <- "Spring"

#as a data.frame, it converts them to v1, v2 and v3, etc.. 
#and eigenvectors (out2$v) with names from the saturation columns
df3 = cbind(as.data.frame(out2$v),names(saturation))
dim(df3)

#rename as saturation
colnames(df3)[colnames(df3)=="names(saturation)"] <- "names"

#get bottom NA out
df2
df3


#and make an awesome plot, we're going to compare PC1 and PC2

ggplot(df2, aes(x = V1, y= V2))+geom_point(aes(colour=Spring),size=6)+
  #first just plotting points and colouring them by the cut
  
  geom_hline(yintercept=0)+geom_vline(xintercept=0)+
  
  #then we'll plot some 0 lines for our reference
  coord_fixed(xlim=c(-4,4),ylim=c(-5,5))+
  
  #and set the scale
  geom_segment(data=df3,aes(x=0,y=0,xend = V1*arrowScale, yend = V2*arrowScale))+
  
  #Now we'll add lines that correspond to our eigen vectors
  geom_text(data=df3,aes(x = V1*arrowScale, y = V2*arrowScale,label=names))
  #and label those lines


ggsave("spring saturation.jpg", width = 15, height = 15, units = "in")

```




#BOX PLOTS AND STUFF ...plot it all

```{r}
saturation

satSave
satSave=satSave[-51,]

###CALCITE!
#normal
ggplot()+geom_point(aes(x=satSave$Formation, y=satSave$Calcite), shape=22, fill="lightgreen", color="black", size=4)+ggtitle("Calcite Saturation for Grand Canyon Formations")+ylab("Calcite Saturation")+xlab(NULL)+theme_bw()+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=20, face="bold", color="black"))

#box plot
ggplot(satSave, aes(Formation, Calcite))+geom_boxplot(fill="lightgreen", color="black")+geom_point(width = 0.3, shape=24, fill="darkgreen", color="black", size=2)+theme_classic()+xlab(NULL)+ggtitle("Calcite Saturation for North Rim Springs")+ylab("Calcite Saturation")+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=20, face="bold", color="black"))


bp1=ggplot(satSave, aes(Formation, Calcite))+geom_boxplot(fill="lightgreen", color="black")+geom_point(width = 0.3, shape=24, fill="darkgreen", color="black", size=2)+theme_classic()+xlab(NULL)+ggtitle("Calcite Saturation for North Rim Springs")+ylab("Calcite Saturation")+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=19, face="bold", color="black"))


```
#Dolomite
```{r}
ggplot()+geom_point(aes(x=satSave$Formation, y=satSave$Dolomite), shape=22, fill="lightblue", color="black", size=4)+ggtitle("Dolomite Saturation for North Rim Springs")+ylab("Dolomite Saturation")+xlab(NULL)+theme_bw()+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=20, face="bold", color="black"))

#box plot
ggplot(satSave, aes(Formation, Dolomite))+geom_boxplot(fill="lightblue", color="black")+geom_point(width = 0.3, shape=24, fill="darkblue", color="black", size=2)+theme_classic()+xlab(NULL)+ggtitle("Dolomite Saturation for North Rim Springs")+ylab("Dolomite Saturation")+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=19, face="bold", color="black"))

bp2=ggplot(satSave, aes(Formation, Dolomite))+geom_boxplot(fill="lightblue", color="black")+geom_point(width = 0.3, shape=24, fill="darkblue", color="black", size=2)+theme_classic()+xlab(NULL)+ggtitle("Dolomite Saturation for North Rim Springs")+ylab("Dolomite Saturation")+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=19, face="bold", color="black"))

```
#Aragonite
```{r}

ggplot()+geom_point(aes(x=satSave$Formation, y=satSave$Aragonite), shape=22, fill="red4", color="black", size=4)+ggtitle("Aragonite Saturation for Grand Canyon Formations")+ylab("Aragonite Saturation")+xlab(NULL)+theme_bw()+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=20, face="bold", color="black"))

#box plot
ggplot(satSave, aes(Formation, Aragonite))+geom_boxplot(fill="red4", color="black")+geom_point(width = 0.3, shape=24, fill="red4", color="black", size=2)+theme_classic()+xlab(NULL)+ggtitle("Aragonite Saturation for North Rim Springs")+ylab("Aragonite Saturation")+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=17, face="bold", color="black"))

bp3=ggplot(satSave, aes(Formation, Aragonite))+geom_boxplot(fill="red4", color="black")+geom_point(width = 0.3, shape=24, fill="red4", color="black", size=2)+theme_classic()+xlab(NULL)+ggtitle("Aragonite Saturation for North Rim Springs")+ylab("Aragonite Saturation")+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=19, face="bold", color="black"))
```
#Anhydrite
```{r}
satSave

ggplot()+geom_point(aes(x=satSave$Formation, y=satSave$Anhydrite), shape=22, fill="orange", color="black", size=4)+ggtitle("Gibbsite Saturation for Grand Canyon Formations")+ylab("Gibbsite Saturation")+xlab(NULL)+theme_bw()+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=20, face="bold", color="black"))

#box plot
ggplot(satSave, aes(Formation, Anhydrite))+geom_boxplot(fill="orange", color="black")+geom_point(width = 0.3, shape=24, fill="darkorange", color="black", size=2)+theme_classic()+xlab(NULL)+ggtitle("Anhydrite Saturation for North Rim Springs")+ylab("Anhydrite Saturation")+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=19, face="bold", color="black"))

bp4=ggplot(satSave, aes(Formation, Anhydrite))+geom_boxplot(fill="orange", color="black")+geom_point(width = 0.3, shape=24, fill="darkorange", color="black", size=2)+theme_classic()+xlab(NULL)+ggtitle("Anhydrite Saturation for North Rim Springs")+ylab("Anhydrite Saturation")+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=19, face="bold", color="black"))

```

#Halite
```{r}

satSave
ggplot()+geom_point(aes(x=satSave$Formation, y=satSave$Halite), shape=22, fill="purple", color="black", size=4)+ggtitle("Halite for Grand Canyon Formations")+ylab("Halite Saturation")+xlab(NULL)+theme_bw()+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=20, face="bold", color="black"))

#box plot
ggplot(satSave, aes(Formation, Halite))+geom_boxplot(fill="purple", color="black")+geom_point(width = 0.3, shape=24, fill="purple", color="black", size=2)+theme_classic()+xlab(NULL)+ggtitle("Halite Saturation for North Rim Springs")+ylab("Halite Saturation")+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=19, face="bold", color="black"))

bp5=ggplot(satSave, aes(Formation, Halite))+geom_boxplot(fill="purple", color="black")+geom_point(width = 0.3, shape=24, fill="purple", color="black", size=2)+theme_classic()+xlab(NULL)+ggtitle("Halite Saturation for North Rim Springs")+ylab("Halite Saturation")+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=19, face="bold", color="black"))


```
#Flourite

```{r}

ggplot()+geom_point(aes(x=satSave$Formation, y=satSave$Fluorite), shape=22, fill="brown", color="black", size=4)+ggtitle("Flourite Saturation for Grand Canyon Formations")+ylab("Geothite Saturation")+xlab(NULL)+theme_bw()+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=20, face="bold", color="black"))

#box plot
ggplot(satSave, aes(Formation, Fluorite))+geom_boxplot(fill="brown", color="black")+geom_point(width = 0.3, shape=24, fill="brown", color="black", size=2)+theme_classic()+xlab(NULL)+ggtitle("Fluorite Saturation for North Rim Springs")+ylab("Fluorite Saturation")+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=19, face="bold", color="black"))

bp6=ggplot(satSave, aes(Formation, Fluorite))+geom_boxplot(fill="brown", color="black")+geom_point(width = 0.3, shape=24, fill="brown", color="black", size=2)+theme_classic()+xlab(NULL)+ggtitle("Fluorite Saturation for North Rim Springs")+ylab("Fluorite Saturation")+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=19, face="bold", color="black"))

```
#Co2(g)

```{r}
#rename CO2 and O2
colnames(satSave)[colnames(satSave)=="CO2(g)"] <- "CO2"
colnames(satSave)[colnames(satSave)=="O2(g)"] <- "O2"


#box plot
ggplot(satSave, aes(Formation, CO2))+geom_boxplot(fill="goldenrod2", color="black")+geom_point(width = 0.3, shape=24, fill="goldenrod2", color="black", size=2)+theme_classic()+xlab(NULL)+ggtitle("CO2 (g) Saturation for North Rim Springs")+ylab("CO2 Saturation")+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=19, face="bold", color="black"))

bp7=ggplot(satSave, aes(Formation, CO2))+geom_boxplot(fill="goldenrod2", color="black")+geom_point(width = 0.3, shape=24, fill="goldenrod2", color="black", size=2)+theme_classic()+xlab(NULL)+ggtitle("CO2 (g) Saturation for North Rim Springs")+ylab("CO2 Saturation")+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=19, face="bold", color="black"))

```
#O2
```{r}
ggplot()+geom_point(aes(x=satSave$Formation, y=satSave$O2), shape=22, fill="darkblue", color="black", size=4)+ggtitle("O2 for Grand Canyon Formations")+ylab("O2 Saturation")+xlab(NULL)+theme_bw()+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=20, face="bold", color="black"))

#box plot
ggplot(satSave, aes(Formation, O2))+geom_boxplot(fill="royalblue4", color="black")+geom_point(width = 0.3, shape=24, fill="royalblue4", color="black", size=2)+theme_classic()+xlab(NULL)+ggtitle("O2 Saturation for North Rim Springs")+ylab("O2 Saturation")+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=19, face="bold", color="black"))

bp9=ggplot(satSave, aes(Formation, O2))+geom_boxplot(fill="royalblue4", color="black")+geom_point(width = 0.3, shape=24, fill="royalblue4", color="black", size=2)+theme_classic()+xlab(NULL)+ggtitle("O2 (g) Saturation for North Rim Springs")+ylab("O2 Saturation")+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=19, face="bold", color="black"))
```
#gypsum

```{r}

ggplot(satSave, aes(Formation, Gypsum))+geom_boxplot(fill="red2", color="black")+geom_point(width = 0.3, shape=24, fill="red2", color="black", size=2)+theme_classic()+xlab(NULL)+ggtitle("Gypsum Saturation for North Rim Springs")+ylab("Gypsum Saturation")+theme_bw()+
theme(axis.title.y=element_text(size=15),axis.text.y=element_text(size=12),axis.title.x=element_text(size=16), plot.title=element_text(size=17, face="bold", color="black"))

ggsave("gypsum saturation.jpg")

```

#combine the graphs
```{r}
#gridsssss
library(grid)
library(gridExtra)

#Calcite and Dolomite
bp1= ggplot_gtable(ggplot_build(bp1))
bp2= ggplot_gtable(ggplot_build(bp2))

maxWidth = unit.pmax(bp1$widths[2:3], bp2$widths[2:3])

bp1$widths[2:3] <- maxWidth
bp2$widths[2:3] <- maxWidth


ga1=grid.arrange(bp1, bp2, ncol = 1 )



ggsave("calcite and dolomite.jpg", ga1)


#aragonite and anhydrite
bp3= ggplot_gtable(ggplot_build(bp3))
bp4= ggplot_gtable(ggplot_build(bp4))

maxWidth = unit.pmax(bp3$widths[2:3], bp4$widths[2:3])

bp3$widths[2:3] <- maxWidth
bp4$widths[2:3] <- maxWidth

ga2=grid.arrange(bp3, bp4, ncol = 1)
ggsave("aragonite and anhydrite.jpg", ga2)

#halite and fluorite
bp5= ggplot_gtable(ggplot_build(bp5))
bp6= ggplot_gtable(ggplot_build(bp6))

maxWidth = unit.pmax(bp5$widths[2:3], bp6$widths[2:3])

bp5$widths[2:3] <- maxWidth
bp6$widths[2:3] <- maxWidth

ga3=grid.arrange(bp5, bp6, ncol = 1)

ggsave("halite and fluorite.jpg", ga3)

#CO2 (g) and O2 (G)
bp7= ggplot_gtable(ggplot_build(bp7))
bp9= ggplot_gtable(ggplot_build(bp9))

maxWidth = unit.pmax(bp7$widths[2:3], bp9$widths[2:3])

bp7$widths[2:3] <- maxWidth
bp9$widths[2:3] <- maxWidth

ga4=grid.arrange(bp7, bp9, ncol = 1)

ggsave("co2 and 02.jpg", ga4)
```
#Correlations

```{r}
library(tidyverse)
library(corrplot)
satCor <- read_csv("~/GitHub/EEDA18/geo_Chem/realSat.csv", 
    col_types = cols(Formation = col_skip(), 
        Season = col_skip(), Spring = col_skip()))

satCor=satCor[-1]
satCor=as.data.frame(satCor)

satCor=na.remove(satCor)

m=cor(satCor,use="pairwise.complete.obs")
corrplot(m, method="number")

class(mtcars)
```
#saturation with time

```{r}
timeSat <- read_csv("~/GitHub/EEDA18/geo_Chem/realSat.csv", 
    col_types = cols(Date = col_date(format = "%m/%d/%Y"), 
        Season = col_skip(), X3 = col_skip()))
timeSat=timeSat[-53,]
timeSat

ggplot(timeSat)+geom_jitter(aes(Date, Calcite, shape=factor(Formation), color=factor(Formation)), size=3)+geom_smooth(aes(Date, Calcite), color="black")+ ggtitle("Calcite Saturation with Time")+xlab(NULL) +ylab("Calcite Saturation Index")+labs(color="Unit of Discharge", shape="Unit of Discharge")+theme_bw()+
theme(axis.text.x=element_text(size=14), axis.title.y=element_text(size=16),axis.text.y=element_text(size=14),axis.title.x=element_text(size=16), plot.title=element_text(size=20, face="bold", color="black"))




geom_jitter(aes(Date, Dolomite, shape=factor(Formation), color=factor(Formation)), size=3)+geom_jitter(aes(Date, Aragonite, shape=factor(Formation), color=factor(Formation)), size=3)+geom_jitter(aes(Date, Anhydrite, shape=factor(Formation), color=factor(Formation)), size=3)+

```
#Calcite
```{r}
ggplot(timeSat)+geom_jitter(aes(Date, Calcite, shape=factor(Formation), color=factor(Formation)), size=3)+geom_smooth(aes(Date, Calcite), color="black")+ ggtitle("Calcite Saturation with Time")+xlab(NULL) +ylab("Calcite Saturation Index")+labs(color="Unit of Discharge", shape="Unit of Discharge")+theme_bw()+
theme(axis.text.x=element_text(size=14), axis.title.y=element_text(size=16),axis.text.y=element_text(size=14),axis.title.x=element_text(size=16), plot.title=element_text(size=20, face="bold", color="black"))

ggsave("calcite with time.jpg")
```
#aragonite
```{r}
ggplot(timeSat)+geom_jitter(aes(Date, Aragonite, shape=factor(Formation), color=factor(Formation)), size=3)+geom_smooth(aes(Date, Aragonite), color="black")+ ggtitle("Aragonite Saturation with Time")+xlab(NULL) +ylab("Aragonite Saturation Index")+labs(color="Unit of Discharge", shape="Unit of Discharge")+theme_bw()+
theme(axis.text.x=element_text(size=14), axis.title.y=element_text(size=16),axis.text.y=element_text(size=14),axis.title.x=element_text(size=16), plot.title=element_text(size=20, face="bold", color="black"))

ggsave("aragonite with time.jpg")

```
#dolomite
```{r}
ggplot(timeSat)+geom_jitter(aes(Date, Dolomite, shape=factor(Formation), color=factor(Formation)), size=3)+geom_smooth(aes(Date, Dolomite), color="black")+ ggtitle("Dolomite Saturation with Time")+xlab(NULL) +ylab("Dolomite Saturation Index")+labs(color="Unit of Discharge", shape="Unit of Discharge")+theme_bw()+
theme(axis.text.x=element_text(size=14), axis.title.y=element_text(size=16),axis.text.y=element_text(size=14),axis.title.x=element_text(size=16), plot.title=element_text(size=20, face="bold", color="black"))

ggsave("dolomite with time.jpg")

```
#anhydrite
```{r}
ggplot(timeSat)+geom_jitter(aes(Date, Anhydrite, shape=factor(Formation), color=factor(Formation)), size=3)+geom_smooth(aes(Date, Anhydrite), color="black")+ ggtitle("Anhydrite Saturation with Time")+xlab(NULL) +ylab("Anhydrite Saturation Index")+labs(color="Unit of Discharge", shape="Unit of Discharge")+theme_bw()+
theme(axis.text.x=element_text(size=14), axis.title.y=element_text(size=16),axis.text.y=element_text(size=14),axis.title.x=element_text(size=16), plot.title=element_text(size=20, face="bold", color="black"))

ggsave("anhydrite with time.jpg")

```
#halite
```{r}
ggplot(timeSat)+geom_jitter(aes(Date, Halite, shape=factor(Formation), color=factor(Formation)), size=3)+geom_smooth(aes(Date, Halite), color="black")+ ggtitle("Halite Saturation with Time")+xlab(NULL) +ylab("Halite Saturation Index")+labs(color="Unit of Discharge", shape="Unit of Discharge")+theme_bw()+
theme(axis.text.x=element_text(size=14), axis.title.y=element_text(size=16),axis.text.y=element_text(size=14),axis.title.x=element_text(size=16), plot.title=element_text(size=20, face="bold", color="black"))

ggsave("anyhydrite with time.jpg")

```
#gypsum
```{r}
ggplot(timeSat)+geom_jitter(aes(Date, Gypsum, shape=factor(Formation), color=factor(Formation)), size=3)+geom_smooth(aes(Date, Gypsum), color="black")+ ggtitle("Gypsum Saturation with Time")+xlab(NULL) +ylab("Gypsum Saturation Index")+labs(color="Unit of Discharge", shape="Unit of Discharge")+theme_bw()+
theme(axis.text.x=element_text(size=14), axis.title.y=element_text(size=16),axis.text.y=element_text(size=14),axis.title.x=element_text(size=16), plot.title=element_text(size=20, face="bold", color="black"))
?geom_smooth()

ggsave("gypsum with time.jpg")
```



